### ISSUE TITLE
Getting error message "E_SYSTEM_INFO_FAILED | CODE:undefined" while reading Tag's SystemInfo

### ISSUE THREAD

**Issue by SantoshSah** [valentiniljaz/cordova-nfcv-plugin#1]
Hello @valentiniljaz ,

I have carried over our conversation from https://github.com/chariotsolutions/phonegap-nfc/issues/195#issuecomment-291551518.

I am able to use single intent after setting parameter value from ```true``` to ```false``` but getting same error message ```E_SYSTEM_INFO_FAILED | CODE:undefined``` every time i move mobile to tag.

**Comment by valentiniljaz** [comment]
Hi @SantoshSah,

The `getSystemInfo` method should print out in the console what was read from the tag. You should see something like:
```
** SYSTEM INFO END **
... byte array od read data ...
```
Could you please paste this printout.

**Comment by SantoshSah** [comment]
Hello @valentiniljaz ,

Console output:

```javascript
** SYSTEM INFO START **
** SYSTEM INFO END ** Uint8Array(1)
Error reading: E_SYSTEM_INFO_FAILED | CODE: undefined
```

Please see detail in below screenshot.
<img width="591" alt="systeminfo_error" src="https://cloud.githubusercontent.com/assets/2204972/24836761/543d7108-1d44-11e7-9860-121f0b0f9d4c.png">

I am using below code:

```javascript
      this.nfcvService.waitForTag();
      this.nfcvService.onTag(
          (tag) => {
              console.log('Found tag', tag);
                this.nfcvService
                .getSystemInfo(false)
                .then((systemInfo) => {
                    console.log('SystemInfo:', systemInfo); // Check the tag's UID and AFI (optionally)
                    this.nfcvService.waitForTag();
                })
                .catch((error) => {
                    console.log('Error reading:', error);
                    this.nfcvService.waitForTag();
                });
            
          },
          (error) => {
              console.log('Error on tag', error);
              this.nfcvService.waitForTag();
          });
```

**Comment by valentiniljaz** [comment]
The return value of `getSystemInfo` should be an array of bytes, where the first byte should be `0`. In your case you received value of `3`, which means there was an error reading system info. Value `3` also tells you what kind of error occurred, but to know for sure I would need the datasheet of your tag. Have you, by any chance, received the datasheet from the manufacturer?
