### ISSUE TITLE
How to write ?

### ISSUE THREAD

**Issue by lucydjo** [valentiniljaz/cordova-nfcv-plugin#12]
Hello,

I managed to follow the documentation to read my NFC tag, but I don't know how to write.

Can you help me?

I use cordova.

```
NfcV.startListening(function (data) {
            try {

            	let addr = new Uint8Array([0x01]);
            	let bdata = new Uint8Array([0x01, 0x02, 0x03, 0x04]);

	            NfcV.writeBlock( addr, bdata, function(){ 
	            	console.log('Cool')
	            }, function(e){ 
	            	console.log(e)
	            } );
	        }
	        catch(err) {
	            console.log(err);
	            alert(err.message);
	        }
        }, function (error) {
            console.log(error);
        });
```

Thx

**Comment by lucydjo** [comment]
up ?

**Comment by valentiniljaz** [comment]
Your code looks ok, but could you provide more context and maybe some debugging info (e.g. console printouts).

You can also check out function "write" within NfcvService used for Ionic; it implements a bit more elaborate case and it might help you pinpoint your issue:
https://github.com/valentiniljaz/cordova-nfcv-plugin/blob/master/ionic2/src/nfcv.service.ts

Hope it helps.
