### ISSUE TITLE
npm install script fails

### ISSUE THREAD

**Issue by psyfreak** [valentiniljaz/cordova-nfcv-plugin#2]
Hello,
 in general I would love your plugin bringing nfcv to ionic2, but ....
i tried to install your script via npm, via add https or via local and I always run into the below error:
Furthermore I ran before into an issue, that tsc could not executed, so I installed typesscript.
This might be a good extension to the documentation.

Thank you very much upfront for your answer.

 Error: cmd: Command failed with exit code 1 Error output:
        npm ERR! addLocal Could not install [uglified]\dev\ionic\cordova-nfcv-plugin
        npm ERR! Windows_NT 6.1.7601
        npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "[uglified]\\dev\\ionic\\cordova-nfcv-plugin" "--save"
        npm ERR! node v6.10.3
        npm ERR! npm  v3.10.10
        npm ERR! code ELIFECYCLE
        npm ERR! cordova-nfcv-plugin@0.1.0 prepublish: `tsc --project ./ionic2`
        npm ERR! Exit status 2
        npm ERR!
        npm ERR! Failed at the cordova-nfcv-plugin@0.1.0 prepublish script 'tsc --project ./ionic2'.
        npm ERR! Make sure you have the latest version of node.js and npm installed.
        npm ERR! If you do, this is most likely a problem with the cordova-nfcv-plugin package,
        npm ERR! not with npm itself.
        npm ERR! Tell the author that this fails on your system:
        npm ERR!     tsc --project ./ionic2
        npm ERR! You can get information on how to open an issue for this project with:
        npm ERR!     npm bugs cordova-nfcv-plugin
        npm ERR! Or if that isn't available, you can get their info via:
        npm ERR!     npm owner ls cordova-nfcv-plugin
        npm ERR! There is likely additional logging output above.

**Comment by psyfreak** [comment]
it seems to work with cordova plugin add but not with ionic cordova plugin add....
that is weird...

**Comment by BernardUriza** [comment]
I have the same issue!

**Comment by valentiniljaz** [comment]
There was a type error within typescript code which is now fixed. NPM INSTALL and CORODVA PLUGIN ADD should all now work.

**Comment by BernardUriza** [comment]
valentiniljaz YEEES It's working for me!
Thanks for all this support
