### ISSUE TITLE
Failed to compile TSC

### ISSUE THREAD

**Issue by PaulCannell** [valentiniljaz/cordova-nfcv-plugin#7]
HI,

Im wanting to use your plugin to write to an NFC device. However Im using ionic 3.20 and node 8.11 vs angular 2.

I did the plugin add and when i did ionic serve or ionic cordova build android I get the following error
Error: ./node_modules/cordova-nfcv-plugin/ionic2/src/nfcv.service.ts
Module build failed: Error: ENOENT: no such file or directory, open '/Users/paulcannell/git/RealTelematics/nfc/node_modules/cordova-nfcv-plugin/ionic2/src/nfcv.service.js

I then cloned your repo into a seperate folder and ran npm i which build your project and all the js files were present. 
I get lots of errors that look like the one below (complete list in attached file)
Class 'HotObservable<T>' incorrectly extends base class 'Subject<T>'. Types of property '_subscribe' are
            incompatible. Type '(subscriber: Subscriber<any>) => Subscription' is not assignable to type '(subscriber:
            Subscriber<T>) => Subscription'. Types of parameters 'subscriber' and 'subscriber' are incompatible. Type
            'Subscriber<T>' is not assignable to type 'Subscriber<any>'. Property 'isStopped' is protected but type
            'Subscriber<T>' is not a class derived from 'Subscriber<T>'

I then noticed I was using a  rxjs v5.5.11 vs your 5.2 so I updated in your project and tried again. Same result.
What confuses me is I can tsc your project with no errors but once I try and consume it in the ionic project it fails miserably.
If you wish I can put the project on github but as I said it was an "ionic start myApp blank"
You seem to be the only library for nfcv and I would be most grateful if you could assist.
- Paul Cannell

[errors.txt](https://github.com/valentiniljaz/cordova-nfcv-plugin/files/2218124/errors.txt)

**Comment by valentiniljaz** [comment]
Hi,

sorry for late response - vacation time :-)

The library was tested only with Ionic 2. In the following days I will try to upgrade the library to work with newer versions of Ionic, specifically 3.2.

I'll let you know as soon as I'll make any progress.

**Comment by PaulCannell** [comment]
Thanx muchly. Im now just using the underlying plugin directly but the typescript is a nicer alternative. I should thank you for not keeping it up to date as I had to dive into the plugin myself :)
